workflows:
  android:
    name: Android Workflow
    environment:
      groups:
        - android
      python_version: 3.9
    scripts:
      - pip install buildozer
      - buildozer android debug
